name: Check Cluster

on: [push]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          sudo apt-get -y update
          sudo apt-get -y install python-dev python-pip
          sudo pip install --upgrade pip
          sudo pip install python-openstackclient
          export OS_AUTH_URL=${{secrets.OS_AUTH_URL}}
          export OS_PROJECT_NAME=${{secrets.OS_PROJECT_NAME}}
          export OS_PROJECT_DOMAIN_ID=${{secrets.OS_PROJECT_DOMAIN_ID}}
          export OS_USER_DOMAIN_NAME=${{secrets.OS_USER_DOMAIN_NAME}}
          export OS_USERNAME=${{secrets.OS_PROJECT_NAME}}
          export OS_PASSWORD=${{secrets.PASSWORD}}
          openstack network list
          openstack coe cluster create vks-test --cluster-template k8s_1.14.1 \
            --master-count 1 \
            --node-count 1 \
            --master-flavor VC-2 \
            --flavor VC-2 \
            --keypair mykey \
            --labels cloud_provider_tag=v1.14.0,coredns_tag=1.5.2,kube_tag=v1.14.1,heat_container_agent_tag=stein-stable
          
      - run: echo One last message
