name: Check Cluster

on: [push]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          
          sudo apt-get -y update
          sudo apt-get -y install python-dev python-pip
          sudo pip install --upgrade pip
          sudo pip install python-openstackclient
          export OS_PASSWORD= ${{secrets.PASSWORD}}
          export OS_AUTH_URL= ${{secrets.OS_AUTH_URL}}
          export OS_PROJECT_NAME= ${{secrets.OS_PROJECT_NAME}}
          export OS_USERNAME= ${{secrets.OS_USERNAME}}
          export OS_USER_DOMAIN_NAME= ${{secrets.OS_USER_DOMAIN_NAME}}
          openstack network list
          
          
      - run: echo One last message
