name: Check Cluster

on: [push]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          sudo apt-get -y update
          sudo apt-get -y install python-dev python-pip
          sudo pip install --upgrade pip
          openstack complete | sudo tee /etc/bash_completion.d/osc.bash_completion > /dev/null
      - run: echo One last message