name: Check Cluster

on: [push]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          
          sudo apt-get -y update
          sudo apt-get -y install python-dev python-pip
          sudo pip install --upgrade pip
          sudo pip install python-openstackclient
          . vks-test-openrc.sh
          
      - run: echo One last message
