name: Check Cluster

on: [push]


jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install CLI
      env:
        OS_AUTH_URL: ${{secrets.OS_AUTH_URL}}
        OS_PROJECT_NAME: ${{secrets.OS_PROJECT_NAME}}
        OS_PROJECT_DOMAIN_ID: ${{secrets.OS_PROJECT_DOMAIN_ID}}
        OS_USER_DOMAIN_NAME: ${{secrets.OS_USER_DOMAIN_NAME}}
        OS_USERNAME: ${{secrets.OS_PROJECT_NAME}}
        OS_PASSWORD: ${{secrets.PASSWORD}}
        KUBECONFIG: ./config
      run: |
        sudo apt-get -y update
        sudo apt-get -y install python-dev python-pip
        sudo pip install --upgrade pip
        sudo pip install python-openstackclient
        sudo pip install python-magnumclient


