name: Check Cluster

on: [push]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          sudo -s
          apt-get -y update
          apt-get -y install python-dev python-pip
          pip install --upgrade pip
          pip install python-openstackclient
          bash vks-test-openrc.sh -x
          . vks-test-openrc.sh
          openstack network list
          
      - run: echo One last message
