name: Check Cluster
#test
on: [push]
  #schedule:
    #- cron:  '0 * * * *'
jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Openstack CLI and python k8s library
      run: |
        sudo apt-get -y update
        sudo apt-get -y install python-dev python-pip
        sudo pip install --upgrade pip
        sudo pip install python-openstackclient
        sudo pip install requests
        sudo pip install python-magnumclient
        sudo pip install kubernetes
        
    - name: Creating K8s cluster
      env:
        OS_AUTH_URL: ${{secrets.OS_AUTH_URL}}
        OS_PROJECT_NAME: ${{secrets.OS_PROJECT_NAME}}
        OS_PROJECT_DOMAIN_ID: ${{secrets.OS_PROJECT_DOMAIN_ID}}
        OS_USER_DOMAIN_NAME: ${{secrets.OS_USER_DOMAIN_NAME}}
        OS_USERNAME: ${{secrets.OS_PROJECT_NAME}}
        OS_PASSWORD: ${{secrets.PASSWORD}}
        OS_CLUSTER_NAME: ${{secrets.OS_CLUSTER_NAME}}
        OS_TELEGRAM_TOKEN : ${{secrets.OS_TELEGRAM_TOKEN}}
        OS_TELEGRAM_CHAT_ID: ${{secrets.OS_TELEGRAM_CHAT_ID}}
      run: |
        openstack coe cluster create $OS_CLUSTER_NAME --cluster-template k8s_1.15.6_at29_stable --master-count 1 --node-count 1 --master-flavor VC-2 --flavor VC-2 --keypair mykey
        python check_cluster_creation.py
    - name: Get cluster config
      env:
        KUBECONFIG: ./config
      run: |
        openstack coe cluster config vks-test
    - name: Check cluster health
      run: |
        python check_pods.py
    
     
